package eu.fr.indyli.formation.business.dto;
// Generated 25 juin 2017 02:21:10 by Hibernate Tools 5.2.0.CR1

import java.util.Date;

/**
 * Comment generated by hbm2java
 */
public class EcolisCommentDto extends AbstractEcolisEntity implements IEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = 35991431279109549L;
	private Integer commentId;
	private EcolisUserDto user;
	private String corps;
	private Date creationDate;

	public EcolisCommentDto() {
	}

	public EcolisCommentDto(EcolisUserDto user, Date creationDate) {
		this.user = user;
		this.creationDate = creationDate;
	}

	public EcolisCommentDto(EcolisUserDto user, String corps, Date creationDate) {
		this.user = user;
		this.corps = corps;
		this.creationDate = creationDate;
	}
	
	@Override
	public Integer getId() {
		return this.commentId;
	}

	@Override
	public void setId(Integer id) {
		this.commentId = id;
	}

	public EcolisUserDto getUser() {
		return user;
	}

	public void setUser(EcolisUserDto user) {
		this.user = user;
	}

	public String getCorps() {
		return corps;
	}

	public void setCorps(String corps) {
		this.corps = corps;
	}

	public Date getCreationDate() {
		return creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}
}
